import type { NextPage } from 'next';
import Head from 'next/head';
import AboutUs from '../components/about_us';
import ContactUs from '../components/contact-us';
import MastHead from '../components/masthead';
import Skills from '../components/skills';
import TrustedBy from '../components/trusted_by';
import Works from '../components/works';

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Beatitudo</title>
        {/* <meta name='description' content='Generated by create next app' /> */}
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <MastHead />
      <AboutUs />
      <Skills />
      <Works />
      <TrustedBy />
      <ContactUs />
    </div>
  );
};

export default Home;
