import type { NextPage } from "next";
import Head from "next/head";
import AboutUs from "../components/about_us";
import MastHead from "../components/masthead";
import Skills from "../components/skills";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Beatitudo</title>
        {/* <meta name='description' content='Generated by create next app' /> */}
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MastHead />
      <AboutUs />
      <Skills />
      <div className="font-bold text-8xl text-white">Hello</div>
    </div>
  );
};

export default Home;
